# Generated by Django 3.0.3 on 2020-07-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleTodo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='task_status',
            field=models.BooleanField(default=False),
        ),
    ]
